on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]
    branches:
      - 'master/**'
  workflow_dispatch:
  
jobs:
  check_idea_file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Check .idea existence
        id: check_files
        uses: thebinaryfelix/check-file-existence-action@1.0.0
        with:
          files: '.idea'

      - name: Folder exist
        if: steps.check_idea_file_existence.outputs.exists == 'true'
        run: echo "Folder .idea exists."
        run: exit 1
