on:
  pull_request:
    types: [synchronize, opened, reopened, edited, labeled, unlabeled]
    branches:
      - 'master/**'
  workflow_dispatch:
  
jobs:
  check_idea_file_existence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check .idea folder exists
        run: |
          ls -la
          if [ -a ".idea" ]; then exit 1; else exit 0; fi
