on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]
    branches:
      - 'master/**'
  workflow_dispatch:
  
jobs:
  check_idea_file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Check .idea existence
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: '.idea'
          fail: false

      - name: Folder exist
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          echo "Folder .idea exists."
          exit 1
